{
 "title": "Overview",
 "time": { "from": "2019-12-16T07:18:40.077Z", "to": "2019-12-16T07:19:33.150Z" },
 "templating": {
  "list": [
   {
    "name": "SYS",
    "query": "SELECT DISTINCT sys from bbq_ids;"
   },
   {
    "name": "GROUP",
    "query": "select distinct bbq_group from bbq_ids where sys  = $SYS;"
   },
   {
    "name": "cpu",
    "query": "select id from bbq_ids where type_string = 'CPU' and sys = $SYS and bbq_group = $GROUP "
   },
   {
    "name": "mem",
    "query": "select id from bbq_ids where type_string = 'MEM' and sys = $SYS and bbq_group = $GROUP "
   },
   {
    "name": "net",
    "query": "select id from bbq_ids where type_string = 'NET' and sys = $SYS and bbq_group = $GROUP "
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU $cpu",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "repeat": "cpu",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  occupancy,\n  bbq_load\nFROM bbq_resources\nWHERE\n  bbq_id = $cpu\nORDER BY created_at"
    }
   ]
  },
  {
   "title": "CPU $cpu",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  occupancy,\n  bbq_load\nFROM bbq_resources\nWHERE\n  bbq_id = $cpu\nORDER BY created_at"
    }
   ]
  },
  {
   "title": "CPU $cpu",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  occupancy,\n  bbq_load\nFROM bbq_resources\nWHERE\n  bbq_id = $cpu\nORDER BY created_at"
    }
   ]
  },
  { "title": "NET", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "NET $net",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "repeat": "net",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  bbq_load\nFROM bbq_resources\nWHERE\n  bbq_id = $net\nORDER BY created_at"
    }
   ]
  },
  { "title": "MEM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "MEM $mem",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 14 },
   "repeat": "mem",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  created_at AS \"time\",\n  bbq_load\nFROM bbq_resources\nWHERE\n  bbq_id = $mem\nORDER BY created_at"
    }
   ]
  }
 ]
}